### PR TITLE
v2.00 mastering

### PR DESCRIPTION
**Pull request by m4rc1e**
Hello @rbmntjs,

I've spent the afternoon mastering this one.

fonts are dehinted to match previous release. 
exo-no-pixel-jump

All glyphs from previous release are there, apart from this one:
screen shot 2017-02-23 at 16 16 10

Windows vertical metrics are now the same as previous release. USE_TYPO_METRICS was enabled to stop the fonts clipping in windows. Win desc and Win asc are now font bbox.
screen shot 2017-02-23 at 16 15 47

I'll check the metadata tomorrow but I'm pretty happy.

cc @davelab6

### CODE REVIEW

**Comment by rbmntjs** [comment]
Thanks, Marc. This looks great. The only note I have is that `uni0338` isn’t supposed to be a slashed zero. It’s a zero width combining mark, and that’s definitely a different sort of glyph. We try to retain legacy, but in this case it’s a very strong error. It means that someone has to encode, for example, the string 199̸ in order to achieve the typographic 1990 with slashed zero. I strongly doubt any current Exo user has performed that action, and slashed zero is now properly implement as a feature. So I propose that we break legacy here. Would love to hear from @davelab6 as well.

**Comment by m4rc1e** [comment]
uni0338 doesn't exist. This is a glyph from the panose substitution font. I'm in complete agreement that it was wrong in the legacy so I'm ignoring it.

**Comment by rbmntjs** [comment]
Oh, yeah, I mean that it’s like that in Unicode. I didn’t include the glyph because it’s only used once (Ø), and Unicode have stated that O+uni0338 is not a valid decomposition of Ø (it doesn’t have one) – so the use case is very limited. I doubt we’ll see very many strings of numbers that include .notdef instead of a slashed zero.

**Comment by rbmntjs** [comment]
I’m going to pull this, as it’s been a week and Dave has been quiet. Hopefully we can get to release ASAP.

**Comment by davelab6** [comment]
Thanks! I'm in total agreement

**Comment by m4rc1e** [comment]
@rbmntjs Thank you sir.

I'll pr this to google/fonts. Your work was great!

**Comment by m4rc1e** [comment]
@NDISCOVER, can we send you a pr for this additional work?

**Comment by NDISCOVER** [comment]
Hi @m4rc1e 

I see you have been testing and working with Exo 2. We are available for some additional work. Please send.

**Comment by m4rc1e** [comment]
@NDISCOVER, This repo is forked from **NDISCOVER/Exo-1.0**

Its a tad confusing but this upgrade has bumped the font family's internal version number up to 2.000. This is simply an upgraded version of Exo-1.0.

I'll send you a pr to your source repository. Play around with it and if you like it, merge it. We can then pr it to fonts/google.

**Comment by NDISCOVER** [comment]
Sorry, there was a misunderstanding here :) 

Exo 1 and Exo 2 are different projects. You can send the pr for the Exo 1. I think the version number should be kept 1.x for clarity sake.

**Comment by m4rc1e** [comment]
Thanks

I'll bump the version number down to avoid confusion.

**Pull request merged**
